- job:
    name: bindep
    description: |
      Check that bindep can install packages.
    roles:
      - zuul: openstack-infra/zuul-jobs
    run: playbooks/bindep/run.yaml
    vars:
      zuul_work_dir: '{{ zuul.project.src_dir }}'
      zuul_work_virtualenv: '{{ ansible_user_dir }}/.venv'

- job:
    name: bindep-centos-7
    parent: bindep
    nodeset: centos-7

- job:
    name: bindep-opensuse-423
    parent: bindep
    nodeset: opensuse-423

- job:
    name: bindep-opensuse-150
    parent: bindep
    nodeset: opensuse-150

- job:
    name: bindep-ubuntu-trusty
    parent: bindep
    nodeset: ubuntu-trusty

- job:
    name: bindep-ubuntu-xenial
    parent: bindep
    nodeset: ubuntu-xenial

- project:
    check:
      jobs:
        - bindep-centos-7
        - bindep-opensuse-423
        - bindep-opensuse-150
        - bindep-ubuntu-trusty
        - bindep-ubuntu-xenial
    gate:
      jobs:
        - bindep-centos-7
        - bindep-opensuse-423
        - bindep-opensuse-150
        - bindep-ubuntu-trusty
        - bindep-ubuntu-xenial
