- job:
    name: bindep-fallback
    description: |
      Check that bindep can install packages from
      openstack-infra/project-config/nodepool/elements/bindep-fallback.txt.
    roles:
      - zuul: openstack-infra/zuul-jobs
    run: playbooks/bindep-fallback/run.yaml
    vars:
      zuul_work_dir: '{{ zuul.project.src_dir }}'
      zuul_work_virtualenv: '{{ ansible_user_dir }}/.venv'

- job:
    name: bindep-fallback-centos-7
    parent: bindep-fallback
    nodeset: centos-7

- job:
    name: bindep-fallback-opensuse-423
    parent: bindep-fallback
    nodeset: opensuse-423

- job:
    name: bindep-fallback-opensuse-150
    parent: bindep-fallback
    nodeset: opensuse-150

- job:
    name: bindep-fallback-ubuntu-trusty
    parent: bindep-fallback
    nodeset: ubuntu-trusty

- job:
    name: bindep-fallback-ubuntu-xenial
    parent: bindep-fallback
    nodeset: ubuntu-xenial

- job:
    name: bindep-build-image
    description: |
      Build a docker image.

      See the `role documentation
      <https://zuul-ci.org/docs/zuul-jobs/roles.html#role-build-docker-image>`_
      for details.
    allowed-projects: openstack-infra/bindep
    pre-run: playbooks/build-image/pre.yaml
    run: playbooks/build-image/run.yaml
    vars:
      images:
        - context: .
          repository: opendevorg/bindep
    files:
      - Dockerfile
      - docker/scripts/.*

- project:
    check:
      jobs:
        - bindep-fallback-centos-7
        - bindep-fallback-opensuse-423
        - bindep-fallback-opensuse-150
        - bindep-fallback-ubuntu-trusty
        - bindep-fallback-ubuntu-xenial
        - bindep-build-image
    gate:
      jobs:
        - bindep-fallback-centos-7
        - bindep-fallback-opensuse-423
        - bindep-fallback-opensuse-150
        - bindep-fallback-ubuntu-trusty
        - bindep-fallback-ubuntu-xenial
        - bindep-build-image
